apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s9qn0mzv0-go-gitops
  description: This is GitOps manifest for s9qn0mzv0-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=s9qn0mzv0-go
    backstage.io/kubernetes-id: s9qn0mzv0-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: s9qn0mzv0-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:s9qn0mzv0-go
