apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s9qn0mzv0-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s9qn0mzv0-go 
  name: s9qn0mzv0-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s9qn0mzv0-go 
